py file added
javadebadi/hep-analysis pull request #1
Opened 2022-01-09 09:15 UTC by VahidHosseinzadeh

I added the main.py which is a sqlalchemy code for creating tables for hep-analysis

2022-01-09 11:43 UTC, javadebadi requested changes
In the 1st line use the following style to import: [link](https://stackoverflow.com/questions/14376900/is-there-a-recommended-format-for-multi-line-imports)

In the 5th line:
Create a new file "settings.py" and add a new variable in that which contains information about connection string such as 
`DB_CONNECTION_STRING = "sqlite+pysqlite:///:memory:"`
Then import the DB_CONNECTION_STRING in this module.

Thank you for your code.
I will review more after you apply these changes.

2022-01-10 15:50 UTC, javadebadi commented on setting.py
> +DB_CONNECTION_STRING = "sqlite+pysqlite:///:memory:"
Nice!

2022-01-10 16:04 UTC, javadebadi requested changes
Hi vahid,
Thank you for previous changes.

I added some more changes to the styles which you can see.

In addition, I have a question about using ORM.
Why do you use the ORM? we can create tables using SQLAlchemy Core without any need to use ORM. Is there any specific reason that you have defined The ORM? Is this because of future needs?

2022-01-10 16:04 UTC, javadebadi commented on main.py
> +        "Jobs",
Please align the names of tables in Table() as the `Columns`.
For example, in `Job_table` definition the `"Jobs"` string is not aligned with Columns in the below

2022-01-10 16:04 UTC, javadebadi commented on main.py
> +    Column('field_title', String(30))
Usually, when we write the elements of a list of parameters of function in a column way, we should add a trailing comma at the end of the last item. For example, here you have `Column('field_title', String(30))` but in google style you need to write `Column('field_title', String(30)),`.

2022-01-10 16:04 UTC, javadebadi commented on main.py
> +if __name__ == '__mane__':
This must be changed o `if __name__ == '__main__'`

2022-01-11 07:35 UTC, VahidHosseinzadeh commented on main.py
> +        "Jobs",
Hi Javad, Yeah sure.

2022-01-11 07:42 UTC, VahidHosseinzadeh commented on main.py
> +if __name__ == '__mane__':
You mean I should delete `Base.metadata.create_all(engine)`?

2022-01-11 07:45 UTC, VahidHosseinzadeh commented on main.py
> +if __name__ == '__mane__':
oh sorry, why did I write mane :D. yeah got it. why there is no error? it is strange ...

2022-01-11 07:57 UTC, VahidHosseinzadeh commented
> Hi vahid, Thank you for previous changes.
> 
> I added some more changes to the styles which you can see.
> 
> In addition, I have a question about using ORM. Why do you use the ORM? we can create tables using SQLAlchemy Core without any need to use ORM. Is there any specific reason that you have defined The ORM? Is this because of future needs?

I went over the SQLAlchemy document in their site. As you said there are two method for implementing sql in sqlalchemy. 
Core and ORM. as far as I understand, there is no need for object relational mapping (ORM) method unless we want to create a database based on some classes and their objects as tables and instances (rows). We do not need this, right?
a question, I still read the document but let me ask this: now the code is creating the tables through constructing the classes or by the Table command of Core? or both maybe, I mean is it creating two copy of them?

BTW, there is a new version of sqlalchemy (2) on the way.

2022-01-11 09:05 UTC, javadebadi commented
Hi Vahid,
Thank you.
In fact, we can use the ORM of SQLAlchemy.
I will merge your changes to the master branch.

2022-01-11 09:08 UTC, merged